package allan.dev.MagicFridgeAI.model;

public enum Categoria {
    FRUTAS,
    VERDURASLEGUMES,
    CEREAISGRAOS,
    LATICINIOS,
    CARNES,
    OVOS,
    LEGUMINOSAS,
    OLEAGINOSAS,
    TUBERCULOSRAIZES,
    PAESMASSAS,
    DOCESSOBREMESAS,
    BEBIDAS,
    OLEOSEGORDURAS,
    ESPECIARIASTEMPEROS,
    ALIMENTOSPROCESSADOSEMBUTIDOS,
    PRODUTOSPANIFICACAO,
    PRODUTOSINTEGRAIS
}
